// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBO_c-Bj5M8c5L32KX1qXxgqxLoQgnLTo',
    appId: '1:995390798292:web:53f5a46a30aaaa39c0be41',
    messagingSenderId: '995390798292',
    projectId: 'hangisi-app',
    authDomain: 'hangisi-app.firebaseapp.com',
    storageBucket: 'hangisi-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUwFBDWoV6UFYK_-ExhI7ZIvEyopnmbFs',
    appId: '1:995390798292:android:95a932fdb867d31cc0be41',
    messagingSenderId: '995390798292',
    projectId: 'hangisi-app',
    storageBucket: 'hangisi-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgeiguzAiOTm0-RvQoce8nJBxdA_gvU1A',
    appId: '1:995390798292:ios:f3c240daa213a2a0c0be41',
    messagingSenderId: '995390798292',
    projectId: 'hangisi-app',
    storageBucket: 'hangisi-app.firebasestorage.app',
    iosBundleId: 'com.example.hangisiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgeiguzAiOTm0-RvQoce8nJBxdA_gvU1A',
    appId: '1:995390798292:ios:f3c240daa213a2a0c0be41',
    messagingSenderId: '995390798292',
    projectId: 'hangisi-app',
    storageBucket: 'hangisi-app.firebasestorage.app',
    iosBundleId: 'com.example.hangisiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBO_c-Bj5M8c5L32KX1qXxgqxLoQgnLTo',
    appId: '1:995390798292:web:d49b6a92343798c0c0be41',
    messagingSenderId: '995390798292',
    projectId: 'hangisi-app',
    authDomain: 'hangisi-app.firebaseapp.com',
    storageBucket: 'hangisi-app.firebasestorage.app',
  );
}
